config/routes.rb
    put "node/create" => "api/nodes#create"
    get "node/:id/ways" => "api/ways#ways_for_node", :as => :node_ways, :id => /\d+/
    get "node/:id/relations" => "api/relations#relations_for_node", :as => :node_relations, :id => /\d+/
    get "node/:id/history" => "api/old_nodes#history", :as => :api_node_history, :id => /\d+/
    post "node/:id/:version/redact" => "api/old_nodes#redact", :as => :node_version_redact, :version => /\d+/, :id => /\d+/
    get "node/:id/:version" => "api/old_nodes#version", :as => :node_version, :id => /\d+/, :version => /\d+/
    get "node/:id" => "api/nodes#show", :as => :api_node, :id => /\d+/
    put "node/:id" => "api/nodes#update", :id => /\d+/
    delete "node/:id" => "api/nodes#delete", :id => /\d+/
    get "nodes" => "api/nodes#index"

    put "way/create" => "api/ways#create"
    get "way/:id/history" => "api/old_ways#history", :as => :api_way_history, :id => /\d+/
    get "way/:id/full" => "api/ways#full", :as => :way_full, :id => /\d+/
    get "way/:id/relations" => "api/relations#relations_for_way", :as => :way_relations, :id => /\d+/
    post "way/:id/:version/redact" => "api/old_ways#redact", :as => :way_version_redact, :version => /\d+/, :id => /\d+/
    get "way/:id/:version" => "api/old_ways#version", :as => :way_version, :id => /\d+/, :version => /\d+/
    get "way/:id" => "api/ways#show", :as => :api_way, :id => /\d+/
    put "way/:id" => "api/ways#update", :id => /\d+/
    delete "way/:id" => "api/ways#delete", :id => /\d+/
    get "ways" => "api/ways#index"

    put "relation/create" => "api/relations#create"
    get "relation/:id/relations" => "api/relations#relations_for_relation", :as => :relation_relations, :id => /\d+/
    get "relation/:id/history" => "api/old_relations#history", :as => :api_relation_history, :id => /\d+/
    get "relation/:id/full" => "api/relations#full", :as => :relation_full, :id => /\d+/
    post "relation/:id/:version/redact" => "api/old_relations#redact", :as => :relation_version_redact, :version => /\d+/, :id => /\d+/
    get "relation/:id/:version" => "api/old_relations#version", :as => :relation_version, :id => /\d+/, :version => /\d+/
    get "relation/:id" => "api/relations#show", :as => :api_relation, :id => /\d+/
    put "relation/:id" => "api/relations#update", :id => /\d+/
    delete "relation/:id" => "api/relations#delete", :id => /\d+/
    get "relations" => "api/relations#index"

    get "map" => "api/map#index"

    get "trackpoints" => "api/tracepoints#index"

    get "user/:id" => "api/users#show", :id => /\d+/, :as => :api_user
    get "user/details" => "api/users#details"
    get "user/gpx_files" => "api/users#gpx_files"
    get "users" => "api/users#index", :as => :api_users

    resources :user_preferences, :except => [:new, :create, :edit], :param => :preference_key, :path => "user/preferences", :controller => "api/user_preferences" do
      collection do
        put "" => "api/user_preferences#update_all", :as => ""
      end
    end

    post "gpx/create" => "api/traces#create"
    get "gpx/:id" => "api/traces#show", :as => :api_trace, :id => /\d+/
    put "gpx/:id" => "api/traces#update", :id => /\d+/
    delete "gpx/:id" => "api/traces#destroy", :id => /\d+/
    get "gpx/:id/details" => "api/traces#show", :id => /\d+/
    get "gpx/:id/data" => "api/traces#data", :as => :api_trace_data

    # Map notes API
    resources :notes, :except => [:new, :edit, :update], :constraints => { :id => /\d+/ }, :controller => "api/notes", :as => :api_notes do
      collection do
        get "search"
        get "feed", :defaults => { :format => "rss" }
      end

      member do
        post "comment"
        post "close"
        post "reopen"
      end
    end

    post "notes/addPOIexec" => "api/notes#create"
    post "notes/closePOIexec" => "api/notes#close"
    post "notes/editPOIexec" => "api/notes#comment"
    get "notes/getGPX" => "api/notes#index", :format => "gpx"
    get "notes/getRSSfeed" => "api/notes#feed", :format => "rss"
  end

  # Data browsing
  get "/way/:id" => "browse#way", :id => /\d+/, :as => :way
  get "/way/:id/history" => "browse#way_history", :id => /\d+/, :as => :way_history
  get "/node/:id" => "browse#node", :id => /\d+/, :as => :node
  get "/node/:id/history" => "browse#node_history", :id => /\d+/, :as => :node_history
  get "/relation/:id" => "browse#relation", :id => /\d+/, :as => :relation
  get "/relation/:id/history" => "browse#relation_history", :id => /\d+/, :as => :relation_history
  get "/changeset/:id" => "browse#changeset", :as => :changeset, :id => /\d+/
  get "/changeset/:id/comments/feed" => "changeset_comments#index", :as => :changeset_comments_feed, :id => /\d*/, :defaults => { :format => "rss" }
  resources :notes, :path => "note", :only => [:show, :new]

  get "/user/:display_name/history" => "changesets#index"
  get "/user/:display_name/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/user/:display_name/notes" => "notes#index", :as => :user_notes
  get "/history/friends" => "changesets#index", :friends => true, :as => "friend_changesets", :defaults => { :format => :html }
  get "/history/nearby" => "changesets#index", :nearby => true, :as => "nearby_changesets", :defaults => { :format => :html }

  get "/browse/way/:id",                :to => redirect(:path => "/way/%{id}")
  get "/browse/way/:id/history",        :to => redirect(:path => "/way/%{id}/history")
  get "/browse/node/:id",               :to => redirect(:path => "/node/%{id}")
  get "/browse/node/:id/history",       :to => redirect(:path => "/node/%{id}/history")
  get "/browse/relation/:id",           :to => redirect(:path => "/relation/%{id}")
  get "/browse/relation/:id/history",   :to => redirect(:path => "/relation/%{id}/history")
  get "/browse/changeset/:id",          :to => redirect(:path => "/changeset/%{id}")
  get "/browse/note/:id",               :to => redirect(:path => "/note/%{id}")
  get "/user/:display_name/edits",      :to => redirect(:path => "/user/%{display_name}/history")
  get "/user/:display_name/edits/feed", :to => redirect(:path => "/user/%{display_name}/history/feed")
  get "/browse/friends",                :to => redirect(:path => "/history/friends")
  get "/browse/nearby",                 :to => redirect(:path => "/history/nearby")
  get "/browse/changesets/feed",        :to => redirect(:path => "/history/feed")
  get "/browse/changesets",             :to => redirect(:path => "/history")
  get "/browse",                        :to => redirect(:path => "/history")

  # web site
  root :to => "site#index", :via => [:get, :post]
  get "/edit" => "site#edit"
  get "/copyright/:copyright_locale" => "site#copyright"
  get "/copyright" => "site#copyright"
  get "/welcome" => "site#welcome"
  get "/fixthemap" => "site#fixthemap"
  get "/help" => "site#help"
  get "/about/:about_locale" => "site#about"
  get "/about" => "site#about"
  get "/communities" => "site#communities"
  get "/history" => "changesets#index"
  get "/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/history/comments/feed" => "changeset_comments#index", :as => :changesets_comments_feed, :defaults => { :format => "rss" }
  get "/export" => "site#export"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  match "/logout" => "sessions#destroy", :via => [:get, :post]
  get "/offline" => "site#offline"
  get "/key" => "site#key"
  get "/id" => "site#id"
  get "/query" => "browse#query"
  get "/user/new" => "users#new"
  post "/user/new" => "users#create"
  get "/user/terms" => "users#terms"
  post "/user/save" => "users#save"
  get "/user/:display_name/confirm/resend" => "confirmations#confirm_resend", :as => :user_confirm_resend
  match "/user/:display_name/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm-email" => "confirmations#confirm_email", :via => [:get, :post]
  post "/user/go_public" => "users#go_public"
  match "/user/reset-password" => "passwords#reset_password", :via => [:get, :post], :as => :user_reset_password
  match "/user/forgot-password" => "passwords#lost_password", :via => [:get, :post], :as => :user_forgot_password
  get "/user/suspended" => "users#suspended"

  get "/index.html", :to => redirect(:path => "/")
  get "/create-account.html", :to => redirect(:path => "/user/new")
  get "/forgot-password.html", :to => redirect(:path => "/user/forgot-password")

  # omniauth
  get "/auth/failure" => "users#auth_failure"
  match "/auth/:provider/callback" => "users#auth_success", :via => [:get, :post], :as => :auth_success
  match "/auth/:provider" => "users#auth", :via => [:post, :patch], :as => :auth

  # permalink
  get "/go/:code" => "site#permalink", :code => /[a-zA-Z0-9_@~]+[=-]*/, :as => :permalink

  # rich text preview
  post "/preview/:type" => "site#preview", :as => :preview

  # traces
  resources :traces, :except => [:show]
  get "/user/:display_name/traces/tag/:tag/page/:page" => "traces#index", :page => /[1-9][0-9]*/
  get "/user/:display_name/traces/tag/:tag" => "traces#index"
  get "/user/:display_name/traces/page/:page" => "traces#index", :page => /[1-9][0-9]*/
  get "/user/:display_name/traces" => "traces#index"
  get "/user/:display_name/traces/tag/:tag/rss" => "traces#georss", :defaults => { :format => :rss }
  get "/user/:display_name/traces/rss" => "traces#georss", :defaults => { :format => :rss }
  get "/user/:display_name/traces/:id" => "traces#show", :as => "show_trace"
  get "/user/:display_name/traces/:id/picture" => "traces#picture", :as => "trace_picture"
  get "/user/:display_name/traces/:id/icon" => "traces#icon", :as => "trace_icon"
  get "/traces/tag/:tag/page/:page" => "traces#index", :page => /[1-9][0-9]*/
  get "/traces/tag/:tag" => "traces#index"
  get "/traces/page/:page" => "traces#index", :page => /[1-9][0-9]*/
  get "/traces/tag/:tag/rss" => "traces#georss", :defaults => { :format => :rss }

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :bigint(8)        not null, primary key
#  latitude   :integer          not null
#  longitude  :integer          not null
#  tile       :bigint(8)        not null
#  updated_at :datetime         not null
#  created_at :datetime         not null
#  status     :enum             not null
#  closed_at  :datetime
#
# Indexes
#
#  notes_created_at_idx   (created_at)
#  notes_tile_status_idx  (tile,status)
#  notes_updated_at_idx   (updated_at)
#

class Note < ApplicationRecord
  include GeoRecord

  has_many :comments, -> { left_joins(:author).where(:visible => true, :users => { :status => [nil, "active", "confirmed"] }).order(:created_at) }, :class_name => "NoteComment", :foreign_key => :note_id
  has_many :all_comments, -> { left_joins(:author).order(:created_at) }, :class_name => "NoteComment", :foreign_key => :note_id, :inverse_of => :note

  validates :id, :uniqueness => true, :presence => { :on => :update },
                 :numericality => { :on => :update, :only_integer => true }
  validates :latitude, :longitude, :numericality => { :only_integer => true }
  validates :closed_at, :presence => true, :if => proc { :status == "closed" }
  validates :status, :inclusion => %w[open closed hidden]

  validate :validate_position

  scope :visible, -> { where.not(:status => "hidden") }
  scope :invisible, -> { where(:status => "hidden") }

  after_initialize :set_defaults

  DEFAULT_FRESHLY_CLOSED_LIMIT = 7.days

  # Sanity check the latitude and longitude and add an error if it's broken
  def validate_position
    errors.add(:base, "Note is not in the world") unless in_world?
  end

  # Close a note
  def close
    self.status = "closed"
    self.closed_at = Time.now.utc
    save
  end

  # Reopen a note
  def reopen
    self.status = "open"
    self.closed_at = nil
    save
  end

  # Check if a note is visible
  def visible?
    status != "hidden"
  end

  # Check if a note is closed
  def closed?
    !closed_at.nil?
  end

  def freshly_closed?
    return false unless closed?

    Time.now.utc < freshly_closed_until
  end

  def freshly_closed_until
    return nil unless closed?

    closed_at + DEFAULT_FRESHLY_CLOSED_LIMIT
  end

  # Return the author object, derived from the first comment
  def author
    comments.first.author
  end

  # Return the author IP address, derived from the first comment
  def author_ip
    comments.first.author_ip
  end

  private

  # Fill in default values for new notes
  def set_defaults
    self.status = "open" unless attribute_present?(:status)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  layout :map_layout

  before_action :check_api_readable
  before_action :authorize_web
  before_action :require_oauth

  authorize_resource

  before_action :set_locale
  around_action :web_timeout

  ##
  # Display a list of notes by a specified user
  def index
    if params[:display_name]
      if @user = User.active.find_by(:display_name => params[:display_name])
        @params = params.permit(:display_name)
        @title = t ".title", :user => @user.display_name
        @page = (params[:page] || 1).to_i
        @page_size = 10
        @notes = @user.notes
        @notes = @notes.visible unless current_user&.moderator?
        @notes = @notes.order("updated_at DESC, id").distinct.offset((@page - 1) * @page_size).limit(@page_size).preload(:comments => :author)

        render :layout => "site"
      else
        @title = t "users.no_such_user.title"
        @not_found_user = params[:display_name]

        render :template => "users/no_such_user", :status => :not_found, :layout => "site"
      end
    end
  end

  def show
    @type = "note"

    if current_user&.moderator?
      @note = Note.find(params[:id])
      @note_comments = @note.comments.unscope(:where => :visible)
    else
      @note = Note.visible.find(params[:id])
      @note_comments = @note.comments
    end
  rescue ActiveRecord::RecordNotFound
    render :template => "browse/not_found", :status => :not_found
  end

  def new; end
end

app/helpers/note_helper.rb
module NoteHelper
  include ActionView::Helpers::TranslationHelper

  def note_event(event, at, by)
    if by.nil?
      t("notes.show.#{event}_by_anonymous_html",
        :when => friendly_date_ago(at),
        :exact_time => l(at))
    else
      t("notes.show.#{event}_by_html",
        :when => friendly_date_ago(at),
        :exact_time => l(at),
        :user => note_author(by))
    end
  end

  def note_author(author, link_options = {})
    if author.nil?
      ""
    elsif author.status == "deleted"
      t("users.no_such_user.deleted")
    else
      link_to h(author.display_name), link_options.merge(:controller => "/users", :action => "show", :display_name => author.display_name)
    end
  end

  def disappear_in(note)
    date = note.freshly_closed_until
    tag.span(distance_of_time_in_words(date, Time.now.utc), :title => l(date, :format => :friendly))
  end
end

app/views/notes/_notes_paging_nav.html.erb
<p>

<% if @page > 1 %>
<%= link_to t("changesets.changeset_paging_nav.previous"), @params.merge(:page => @page - 1) %>
<% else %>
<%= t("changesets.changeset_paging_nav.previous") %>
<% end %>

| <%= t("changesets.changeset_paging_nav.showing_page", :page => @page) %> |

<% if @notes.size < @page_size %>
<%= t("changesets.changeset_paging_nav.next") %>
<% else %>
<%= link_to t("changesets.changeset_paging_nav.next"), @params.merge(:page => @page + 1) %>
<% end %>

</p>

app/views/notes/index.html.erb
<% content_for :heading do %>
  <h1><%= t ".heading", :user => @user.display_name %></h1>
  <p><%= t ".subheading_html", :user => link_to(@user.display_name, user_path(@user)) %></p>
<% end %>

<% if @notes.empty? %>
  <h4><%= t ".no_notes" %></h4>

<% else %>
  <%= render :partial => "notes_paging_nav" %>

  <table class="table table-sm note_list">
    <thead>
      <tr>
        <th></th>
        <th><%= t ".id" %></th>
        <th><%= t ".creator" %></th>
        <th><%= t ".description" %></th>
        <th><%= t ".created_at" %></th>
        <th><%= t ".last_changed" %></th>
      </tr>
    </thead>
  <% @notes.each do |note| -%>
    <tr<% if note.author == @user %> class="creator"<% end %>>
      <td>
        <% if note.closed? %>
          <%= image_tag("closed_note_marker.png", :alt => "closed", :size => "25x40") %>
        <% else %>
          <%= image_tag("open_note_marker.png", :alt => "open", :size => "25x40") %>
        <% end %>
      </td>
      <td><%= link_to note.id, note %></td>
      <td><%= note_author(note.author) %></td>
      <td><%= note.comments.first.body.to_html %></td>
      <td><%= friendly_date_ago(note.created_at) %></td>
      <td><%= friendly_date_ago(note.updated_at) %></td>
    </tr>
  <% end -%>
  </table>

  <%= render :partial => "notes_paging_nav" %>

<% end -%>

app/views/notes/new.html.erb
<% set_title(t(".title")) %>

<%= render "sidebar_header", :title => t(".title") %>

<div class="note">
  <p class="alert alert-info"><%= t(".intro") %></p>
  <form action="#">
    <input type="hidden" name="lon" autocomplete="off">
    <input type="hidden" name="lat" autocomplete="off">
    <div class="mb-3">
      <textarea class="form-control" name="text" cols="40" rows="10" maxlength="2000" placeholder="<%= t(".advice") %>"></textarea>
    </div>
    <div class="btn-wrapper">
      <input type="submit" name="add" value="<%= t(".add") %>" disabled="1" class="btn btn-primary">
    </div>
  </form>
</div>

app/views/notes/show.html.erb
<% set_title(t(".title", :id => @note.id)) %>

<%= render "sidebar_header", :title => t(".#{@note.status}_title", :note_name => @note.id) %>

<div>
  <h4><%= t(".description") %></h4>
  <div class="note-description">
    <%= h(@note_comments.first.body.to_html) %>
  </div>

  <div class="details" data-coordinates="<%= @note.lat %>,<%= @note.lon %>" data-status="<%= @note.status %>">
    <ul class="list-unstyled">
      <li><%= note_event("opened", @note.created_at, @note.author) %></li>
      <% if @note.status == "closed" %>
        <li><%= note_event(@note.status, @note.closed_at, @note.all_comments.last.author) %></li>
      <% end %>
      <li>
        <%= t "browse.location" %>
        <%= link_to(t(".coordinates_html",
                      :latitude => tag.span(number_with_delimiter(@note.lat), :class => "latitude"),
                      :longitude => tag.span(number_with_delimiter(@note.lon), :class => "longitude")),
                    root_path(:anchor => "map=18/#{@note.lat}/#{@note.lon}")) %>
      </li>
    </ul>
  </div>

  <% if @note_comments.find { |comment| comment.author.nil? } -%>
    <p class='alert alert-warning'><%= t ".anonymous_warning" %></p>
  <% end -%>

  <% if @note_comments.length > 1 %>
    <div class='note-comments'>
      <ul class="list-unstyled">
        <% @note_comments.drop(1).each do |comment| %>
          <li id="c<%= comment.id %>">
            <small class='text-muted'><%= note_event(comment.event, comment.created_at, comment.author) %></small>
            <%= comment.body.to_html %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @note.status == "open" %>
    <% if current_user -%>
      <form class="mb-3" action="#">
        <div class="mb-3">
          <textarea class="form-control" name="text" cols="40" rows="5" maxlength="2000"></textarea>
        </div>
        <div class="btn-wrapper">
          <% if current_user.moderator? -%>
            <%= submit_tag t(".hide"), :name => "hide", :class => "btn btn-light",
                                       :data => { :method => "DELETE",
                                                  :url => api_note_url(@note, "json") } %>
          <% end -%>
          <%= submit_tag t(".resolve"), :name => "close", :class => "btn btn-primary",
                                        :data => { :method => "POST",
                                                   :url => close_api_note_url(@note, "json"),
                                                   :default_action_text => t(".resolve"),
                                                   :comment_action_text => t(".comment_and_resolve") } %>
          <%= submit_tag t(".comment"), :name => "comment", :class => "btn btn-primary", :disabled => true,
                                        :data => { :method => "POST",
                                                   :url => comment_api_note_url(@note, "json") } %>
        </div>
      </form>
    <% end -%>
  <% else %>
    <form class="mb-3" action="#">
      <input type="hidden" name="text" value="" autocomplete="off">
      <div class="btn-wrapper">
        <% if @note.status != "hidden" and current_user and current_user.moderator? -%>
          <input type="submit" name="hide" value="<%= t(".hide") %>" class="btn btn-light" data-method="DELETE" data-url="<%= api_note_url(@note, "json") %>">
        <% end -%>
        <% if current_user -%>
          <input type="submit" name="reopen" value="<%= t(".reactivate") %>" class="btn btn-primary" data-method="POST" data-url="<%= reopen_api_note_url(@note, "json") %>">
        <% end -%>
      </div>
    </form>
  <% end %>

  <% if current_user && current_user != @note.author %>
    <p>
      <small class="text-muted">
        <%= t ".report_link_html", :link => report_link(t(".report"), @note) %>
        <% if @note.status == "open" %>
          <%= t ".other_problems_resolve", :link => report_link(t(".report"), @note) %>
        <% elsif @note.status == "closed" %>
          <%= t ".other_problems_resolved" %>
        <% end %>
      </small>
    </p>
  <% end %>

  <% if @note.freshly_closed? %>
    <small class="text-muted">
      <%= t ".disappear_date_html", :disappear_in => disappear_in(@note) %>
    </small>
  <% end %>
</div>