config/routes.rb
    get "changeset/:id" => "api/changesets#show", :as => :changeset_show, :id => /\d+/
    post "changeset/:id/subscribe" => "api/changesets#subscribe", :as => :changeset_subscribe, :id => /\d+/
    post "changeset/:id/unsubscribe" => "api/changesets#unsubscribe", :as => :changeset_unsubscribe, :id => /\d+/
    put "changeset/:id" => "api/changesets#update", :id => /\d+/
    put "changeset/:id/close" => "api/changesets#close", :as => :changeset_close, :id => /\d+/
    get "changesets" => "api/changesets#query"
    post "changeset/:id/comment" => "api/changeset_comments#create", :as => :changeset_comment, :id => /\d+/
    post "changeset/comment/:id/hide" => "api/changeset_comments#destroy", :as => :changeset_comment_hide, :id => /\d+/
    post "changeset/comment/:id/unhide" => "api/changeset_comments#restore", :as => :changeset_comment_unhide, :id => /\d+/

    put "node/create" => "api/nodes#create"
    get "node/:id/ways" => "api/ways#ways_for_node", :as => :node_ways, :id => /\d+/
    get "node/:id/relations" => "api/relations#relations_for_node", :as => :node_relations, :id => /\d+/
    get "node/:id/history" => "api/old_nodes#history", :as => :api_node_history, :id => /\d+/
    post "node/:id/:version/redact" => "api/old_nodes#redact", :as => :node_version_redact, :version => /\d+/, :id => /\d+/
    get "node/:id/:version" => "api/old_nodes#version", :as => :node_version, :id => /\d+/, :version => /\d+/
    get "node/:id" => "api/nodes#show", :as => :api_node, :id => /\d+/
    put "node/:id" => "api/nodes#update", :id => /\d+/
    delete "node/:id" => "api/nodes#delete", :id => /\d+/
    get "nodes" => "api/nodes#index"

    put "way/create" => "api/ways#create"
    get "way/:id/history" => "api/old_ways#history", :as => :api_way_history, :id => /\d+/
    get "way/:id/full" => "api/ways#full", :as => :way_full, :id => /\d+/
    get "way/:id/relations" => "api/relations#relations_for_way", :as => :way_relations, :id => /\d+/
    post "way/:id/:version/redact" => "api/old_ways#redact", :as => :way_version_redact, :version => /\d+/, :id => /\d+/
    get "way/:id/:version" => "api/old_ways#version", :as => :way_version, :id => /\d+/, :version => /\d+/
    get "way/:id" => "api/ways#show", :as => :api_way, :id => /\d+/
    put "way/:id" => "api/ways#update", :id => /\d+/
    delete "way/:id" => "api/ways#delete", :id => /\d+/
    get "ways" => "api/ways#index"

    put "relation/create" => "api/relations#create"
    get "relation/:id/relations" => "api/relations#relations_for_relation", :as => :relation_relations, :id => /\d+/
    get "relation/:id/history" => "api/old_relations#history", :as => :api_relation_history, :id => /\d+/
    get "relation/:id/full" => "api/relations#full", :as => :relation_full, :id => /\d+/
    post "relation/:id/:version/redact" => "api/old_relations#redact", :as => :relation_version_redact, :version => /\d+/, :id => /\d+/
    get "relation/:id/:version" => "api/old_relations#version", :as => :relation_version, :id => /\d+/, :version => /\d+/
    get "relation/:id" => "api/relations#show", :as => :api_relation, :id => /\d+/
    put "relation/:id" => "api/relations#update", :id => /\d+/
    delete "relation/:id" => "api/relations#delete", :id => /\d+/
    get "relations" => "api/relations#index"

    get "map" => "api/map#index"

    get "trackpoints" => "api/tracepoints#index"

    get "user/:id" => "api/users#show", :id => /\d+/, :as => :api_user
    get "user/details" => "api/users#details"
    get "user/gpx_files" => "api/users#gpx_files"
    get "users" => "api/users#index", :as => :api_users

    resources :user_preferences, :except => [:new, :create, :edit], :param => :preference_key, :path => "user/preferences", :controller => "api/user_preferences" do
      collection do
        put "" => "api/user_preferences#update_all", :as => ""
      end
    end

    post "gpx/create" => "api/traces#create"
    get "gpx/:id" => "api/traces#show", :as => :api_trace, :id => /\d+/
    put "gpx/:id" => "api/traces#update", :id => /\d+/
    delete "gpx/:id" => "api/traces#destroy", :id => /\d+/
    get "gpx/:id/details" => "api/traces#show", :id => /\d+/
    get "gpx/:id/data" => "api/traces#data", :as => :api_trace_data

    # Map notes API
    resources :notes, :except => [:new, :edit, :update], :constraints => { :id => /\d+/ }, :controller => "api/notes", :as => :api_notes do
      collection do
        get "search"
        get "feed", :defaults => { :format => "rss" }
      end

      member do
        post "comment"
        post "close"
        post "reopen"
      end
    end

    post "notes/addPOIexec" => "api/notes#create"
    post "notes/closePOIexec" => "api/notes#close"
    post "notes/editPOIexec" => "api/notes#comment"
    get "notes/getGPX" => "api/notes#index", :format => "gpx"
    get "notes/getRSSfeed" => "api/notes#feed", :format => "rss"
  end

  # Data browsing
  get "/way/:id" => "browse#way", :id => /\d+/, :as => :way
  get "/way/:id/history" => "browse#way_history", :id => /\d+/, :as => :way_history
  get "/node/:id" => "browse#node", :id => /\d+/, :as => :node
  get "/node/:id/history" => "browse#node_history", :id => /\d+/, :as => :node_history
  get "/relation/:id" => "browse#relation", :id => /\d+/, :as => :relation
  get "/relation/:id/history" => "browse#relation_history", :id => /\d+/, :as => :relation_history
  get "/changeset/:id" => "browse#changeset", :as => :changeset, :id => /\d+/
  get "/changeset/:id/comments/feed" => "changeset_comments#index", :as => :changeset_comments_feed, :id => /\d*/, :defaults => { :format => "rss" }
  resources :notes, :path => "note", :only => [:show, :new]

  get "/user/:display_name/history" => "changesets#index"
  get "/user/:display_name/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/user/:display_name/notes" => "notes#index", :as => :user_notes
  get "/history/friends" => "changesets#index", :friends => true, :as => "friend_changesets", :defaults => { :format => :html }
  get "/history/nearby" => "changesets#index", :nearby => true, :as => "nearby_changesets", :defaults => { :format => :html }

  get "/browse/way/:id",                :to => redirect(:path => "/way/%{id}")
  get "/browse/way/:id/history",        :to => redirect(:path => "/way/%{id}/history")
  get "/browse/node/:id",               :to => redirect(:path => "/node/%{id}")
  get "/browse/node/:id/history",       :to => redirect(:path => "/node/%{id}/history")
  get "/browse/relation/:id",           :to => redirect(:path => "/relation/%{id}")
  get "/browse/relation/:id/history",   :to => redirect(:path => "/relation/%{id}/history")
  get "/browse/changeset/:id",          :to => redirect(:path => "/changeset/%{id}")
  get "/browse/note/:id",               :to => redirect(:path => "/note/%{id}")
  get "/user/:display_name/edits",      :to => redirect(:path => "/user/%{display_name}/history")
  get "/user/:display_name/edits/feed", :to => redirect(:path => "/user/%{display_name}/history/feed")
  get "/browse/friends",                :to => redirect(:path => "/history/friends")
  get "/browse/nearby",                 :to => redirect(:path => "/history/nearby")
  get "/browse/changesets/feed",        :to => redirect(:path => "/history/feed")
  get "/browse/changesets",             :to => redirect(:path => "/history")
  get "/browse",                        :to => redirect(:path => "/history")

  # web site
  root :to => "site#index", :via => [:get, :post]
  get "/edit" => "site#edit"
  get "/copyright/:copyright_locale" => "site#copyright"
  get "/copyright" => "site#copyright"
  get "/welcome" => "site#welcome"
  get "/fixthemap" => "site#fixthemap"
  get "/help" => "site#help"
  get "/about/:about_locale" => "site#about"
  get "/about" => "site#about"
  get "/communities" => "site#communities"
  get "/history" => "changesets#index"
  get "/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/history/comments/feed" => "changeset_comments#index", :as => :changesets_comments_feed, :defaults => { :format => "rss" }
  get "/export" => "site#export"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  match "/logout" => "sessions#destroy", :via => [:get, :post]
  get "/offline" => "site#offline"
  get "/key" => "site#key"
  get "/id" => "site#id"
  get "/query" => "browse#query"
  get "/user/new" => "users#new"
  post "/user/new" => "users#create"
  get "/user/terms" => "users#terms"
  post "/user/save" => "users#save"
  get "/user/:display_name/confirm/resend" => "confirmations#confirm_resend", :as => :user_confirm_resend
  match "/user/:display_name/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm-email" => "confirmations#confirm_email", :via => [:get, :post]
  post "/user/go_public" => "users#go_public"
  match "/user/reset-password" => "passwords#reset_password", :via => [:get, :post], :as => :user_reset_password
  match "/user/forgot-password" => "passwords#lost_password", :via => [:get, :post], :as => :user_forgot_password
  get "/user/suspended" => "users#suspended"

  get "/index.html", :to => redirect(:path => "/")
  get "/create-account.html", :to => redirect(:path => "/user/new")
  get "/forgot-password.html", :to => redirect(:path => "/user/forgot-password")

  # omniauth
  get "/auth/failure" => "users#auth_failure"
  match "/auth/:provider/callback" => "users#auth_success", :via => [:get, :post], :as => :auth_success
  match "/auth/:provider" => "users#auth", :via => [:post, :patch], :as => :auth

  # permalink
  get "/go/:code" => "site#permalink", :code => /[a-zA-Z0-9_@~]+[=-]*/, :as => :permalink

  # rich text preview
  post "/preview/:type" => "site#preview", :as => :preview

  # traces
  resources :traces, :except => [:show]
  get "/user/:display_name/traces/tag/:tag/page/:page" => "traces#index", :page => /[1-9][0-9]*/

app/controllers/api/traces_controller.rb
module Api
  class TracesController < ApiController
    before_action :check_database_readable, :except => [:show, :data]
    before_action :check_database_writable, :only => [:create, :update, :destroy]
    before_action :authorize_web
    before_action :set_locale
    before_action :authorize

    authorize_resource

    before_action :check_api_readable, :only => [:show, :data]
    before_action :check_api_writable, :only => [:create, :update, :destroy]
    before_action :offline_error, :only => [:create, :destroy, :data]
    around_action :api_call_handle_error

    def show
      @trace = Trace.visible.find(params[:id])

      head :forbidden unless @trace.public? || @trace.user == current_user
    end

    def create
      tags = params[:tags] || ""
      description = params[:description] || ""
      visibility = params[:visibility]

      if visibility.nil?
        visibility = if params[:public]&.to_i&.nonzero?
                       "public"
                     else
                       "private"
                     end
      end

      if params[:file].respond_to?(:read)
        trace = do_create(params[:file], tags, description, visibility)

        if trace.id
          TraceImporterJob.perform_later(trace)
          render :plain => trace.id.to_s
        elsif trace.valid?
          head :internal_server_error
        else
          head :bad_request
        end
      else
        head :bad_request
      end
    end

    def update
      trace = Trace.visible.find(params[:id])

      if trace.user == current_user
        trace.update_from_xml(request.raw_post)
        trace.save!

        head :ok
      else
        head :forbidden
      end
    end

    def destroy
      trace = Trace.visible.find(params[:id])

      if trace.user == current_user
        trace.visible = false
        trace.save!
        TraceDestroyerJob.perform_later(trace)

        head :ok
      else
        head :forbidden
      end
    end

    def data
      trace = Trace.visible.find(params[:id])

      if trace.public? || trace.user == current_user
        if request.format == Mime[:xml]
          send_data(trace.xml_file.read, :filename => "#{trace.id}.xml", :type => request.format.to_s, :disposition => "attachment")
        elsif request.format == Mime[:gpx]
          send_data(trace.xml_file.read, :filename => "#{trace.id}.gpx", :type => request.format.to_s, :disposition => "attachment")
        elsif trace.file.attached?
          redirect_to rails_blob_path(trace.file, :disposition => "attachment")
        else
          send_file(trace.trace_name, :filename => "#{trace.id}#{trace.extension_name}", :type => trace.mime_type, :disposition => "attachment")
        end
      else
        head :forbidden
      end
    end

    private

    def do_create(file, tags, description, visibility)
      # Sanitise the user's filename
      name = file.original_filename.gsub(/[^a-zA-Z0-9.]/, "_")

      # Create the trace object, falsely marked as already
      # inserted to stop the import daemon trying to load it
      trace = Trace.new(
        :name => name,
        :tagstring => tags,
        :description => description,
        :visibility => visibility,
        :inserted => false,
        :user => current_user,
        :timestamp => Time.now.utc,
        :file => file
      )

      # Save the trace object
      trace.save!

      # Finally save the user's preferred privacy level
      if pref = current_user.preferences.where(:k => "gps.trace.visibility").first
        pref.v = visibility
        pref.save
      else
        current_user.preferences.create(:k => "gps.trace.visibility", :v => visibility)
      end

      trace
    end

    def offline_error
      report_error "GPX files offline for maintenance", :service_unavailable if Settings.status == "gpx_offline"
    end
  end
end

app/helpers/trace_helper.rb
module TraceHelper
  def link_to_tag(tag)
    link_to(tag, :tag => tag, :page => nil)
  end
end

app/views/traces/_description.html.erb
<%= image_tag(url_for(:controller => :traces, :action => :icon, :id => description.id, :display_name => description.user.display_name)) %>
<% if description.size -%>
<%= t ".description_with_count", :count => description.size, :user => description.user.display_name %>
<% else -%>
<%= t ".description_without_count", :user => description.user.display_name %>
<% end -%>

app/views/traces/_trace.html.erb
<tr>
  <td>
    <% if Settings.status != "gpx_offline" %>
      <% if trace.inserted %>
        <a href="<%= url_for :controller => "traces", :action => "show", :id => trace.id, :display_name => trace.user.display_name %>"><img src="<%= url_for :controller => "traces", :action => "icon", :id => trace.id, :display_name => trace.user.display_name %>" border="0" alt="" /></a>
      <% else %>
        <span class="text-danger"><%= t ".pending" %></span>
      <% end %>
    <% end %>
  </td>
  <td>
    <ul class="list-inline mb-0">
      <li class="list-inline-item">
        <%= link_to trace.name, :controller => "traces", :action => "show", :display_name => trace.user.display_name, :id => trace.id %>
      </li>

      <% if trace.inserted? %>
        <li class="list-inline-item">
          <%= t ".count_points", :count => trace.size %>
        </li>
      <% end %>

      <li class="list-inline-item">
        <% badge_class = case trace.visibility
                         when "public", "identifiable" then "success"
                         else "danger"
                         end %>
        <span class="badge bg-<%= badge_class %> text-white"><%= t(".#{trace.visibility}") %></span>
      </li>
    </ul>
    <p class="text-muted mb-0">
      <span title="<%= trace.timestamp %>">
        <%= time_ago_in_words(trace.timestamp, :scope => :"datetime.distance_in_words_ago") %>
      </span>
      <%= t ".by" %> <%= link_to trace.user.display_name, user_path(trace.user) %>
      <% if !trace.tags.empty? %>
        <%= t ".in" %>
        <%= safe_join(trace.tags.collect { |tag| link_to_tag tag.tag }, ", ") %>
      <% end %>
    </p>
    <p class="fst-italic mb-0">
      <%= trace.description %>
    </p>
  </td>
  <td>
    <% if trace.inserted? %>
      <nav class="secondary-actions">
        <ul>
          <li>
            <%= link_to t(".view_map"), { :controller => "site", :action => "index", :mlat => trace.latitude, :mlon => trace.longitude, :anchor => "map=14/#{trace.latitude}/#{trace.longitude}" } %>
          </li>
          <li>
            <%= link_to t(".edit_map"), { :controller => "site", :action => "edit", :gpx => trace.id } %>
          </li>
        </ul>
      </nav>
    <% end %>
  </td>
</tr>

app/views/traces/_trace_paging_nav.html.erb
<nav>
  <ul class="pagination">
    <% if page > 1 %>
      <li class="page-item">
        <%= link_to t(".newer"), params.merge(:page => page - 1), :class => "page-link" %>
      </li>
    <% else %>
      <li class="page-item disabled">
        <span class="page-link"><%= t(".newer") %></span>
      </li>
    <% end %>

    <li class="page-item disabled">
      <span class="page-link"><%= t(".showing_page", :page => page) %></span>
    </li>

    <% if traces.size < page_size %>
      <li class="page-item disabled">
        <span class="page-link"><%= t(".older") %></span>
      </li>
    <% else %>
      <li class="page-item">
        <%= link_to t(".older"), params.merge(:page => page + 1), :class => "page-link" %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/traces/edit.html.erb
<% content_for :heading do %>
  <h1><%= t ".heading", :name => @trace.name %></h1>
<% end %>

<img src="<%= url_for :controller => "traces", :action => "picture", :id => @trace.id, :display_name => @trace.user.display_name %>">

<%= bootstrap_form_for @trace do |f| %>
  <%= f.text_field :name, :disabled => true %>
  <%= f.text_field :description, :maxlength => 255 %>
  <%= f.text_field :tagstring %>
  <%= f.select :visibility,
               [[t("traces.visibility.private"), "private"],
                [t("traces.visibility.public"), "public"],
                [t("traces.visibility.trackable"), "trackable"],
                [t("traces.visibility.identifiable"), "identifiable"]],
               :help => link_to(t(".visibility_help"), t(".visibility_help_url")) %>
  <%= f.primary %>
  <%= link_to t(".cancel"), show_trace_path(@trace.user, @trace), :class => "btn btn-link" %>
<% end %>

app/views/traces/index.html.erb
<% content_for :heading_class, "pb-0" %>
<% content_for :heading do %>
  <h1><%= @title %></h1>
  <nav class="secondary-actions mb-3">
    <ul>
      <li>
        <%= t(".description") %>
      </li>
      <% if params[:tag] %>
        <li>
          <%= link_to t(".remove_tag_filter", :tag => params[:tag]), { :controller => "traces", :action => "index", :display_name => nil, :tag => nil, :page => nil } %>
        </li>
      <% end %>
    </ul>
  </nav>
  <ul class="nav nav-tabs flex-column flex-sm-row">
    <% if @target_user.blank? %>
      <!-- public traces -->
      <li class="nav-item">
        <%= link_to t(".all_traces"), { :controller => "traces", :action => "index", :display_name => nil, :page => nil }, { :class => "nav-link active" } %>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to t(".my_traces"), { :action => "mine", :page => nil }, { :class => "nav-link" } %>
        </li>
      <% end %>
    <% elsif current_user && current_user == @target_user %>
      <li class="nav-item">
        <%= link_to t(".all_traces"), { :controller => "traces", :action => "index", :display_name => nil, :page => nil }, { :class => "nav-link" } %>
      </li>
      <!-- my traces -->
      <li class="nav-item">
        <%= link_to t(".my_traces"), { :action => "mine", :page => nil }, { :class => "nav-link active" } %>
      </li>
    <% else %>
      <!-- public_traces_from @target_user -->
      <li class="nav-item">
        <%= link_to t(".all_traces"), { :controller => "traces", :action => "index", :display_name => nil, :page => nil }, { :class => "nav-link" } %>
      </li>
      <% if current_user && current_user != @target_user %>
        <li class="nav-item">
          <%= link_to t(".my_traces"), { :action => "mine", :page => nil }, { :class => "nav-link" } %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to t(".public_traces_from", :user => @target_user&.display_name), { :action => "mine", :page => nil }, { :class => "nav-link active" } %>
      </li>
    <% end %>

    <li class="nav-item flex-sm-grow-1"></li>
    <li class="nav-item">
      <div class="px-3 py-2 py-sm-0">
        <%= link_to({ :action => :georss, :display_name => @target_user&.display_name, :tag => params[:tag] }, { :class => "btn btn-secondary btn-sm" }) do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="white" viewBox="0 0 16 16">
            <path d="M5.5 12a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-3-8.5a1 1 0 0 1 1-1c5.523 0 10 4.477 10 10a1 1 0 1 1-2 0 8 8 0 0 0-8-8 1 1 0 0 1-1-1zm0 4a1 1 0 0 1 1-1 6 6 0 0 1 6 6 1 1 0 1 1-2 0 4 4 0 0 0-4-4 1 1 0 0 1-1-1z" />
          </svg>
        <% end -%>
        <%= link_to t(".upload_trace"), new_trace_path, :class => "btn btn-secondary btn-sm" %>
      </div>
    </li>
  </ul>
<% end %>

<% content_for :auto_discovery_link_tag do %>
  <%= auto_discovery_link_tag :rss, :action => "georss", :display_name => @target_user&.display_name, :tag => params[:tag] %>
<% end %>

<% if @traces.size > 0 %>
  <%= render "trace_paging_nav", :page => @page, :page_size => @page_size, :traces => @traces, :params => @params %>

  <table id="trace_list" class="table table-borderless table-striped">
    <tbody>
      <%= render @traces %>
    </tbody>
  </table>

  <%= render "trace_paging_nav", :page => @page, :page_size => @page_size, :traces => @traces, :params => @params %>
<% else %>
  <h4><%= t ".empty_html", :upload_link => new_trace_path %></h4>
<% end %>

app/views/traces/new.html.erb
<% content_for :heading do %>
  <h1><%= t ".upload_trace" %></h1>
<% end %>

<%= bootstrap_form_for @trace, :url => { :action => "create" }, :html => { :multipart => true } do |f| %>
  <%= f.file_field :gpx_file, :placeholder => t("helpers.file.prompt") %>
  <%= f.text_field :description, :maxlength => 255 %>
  <%= f.text_field :tagstring %>
  <%= f.select :visibility,
               [[t("traces.visibility.private"), "private"],
                [t("traces.visibility.public"), "public"],
                [t("traces.visibility.trackable"), "trackable"],
                [t("traces.visibility.identifiable"), "identifiable"]],
               :help => link_to(t(".visibility_help"), t(".visibility_help_url")) %>
  <%= f.primary %>
  <%= link_to t(".help"), t(".help_url"), :class => "btn btn-link" %>
<% end %>

app/views/traces/offline.html.erb
<% content_for :heading do %>
  <h1><%= t ".heading" %></h1>
<% end %>

<p><%= t ".message" %></p>

app/views/traces/show.html.erb
<% content_for :heading do %>
  <h1><%= t ".heading", :name => @trace.name %></h1>
<% end %>

<% if Settings.status != "gpx_offline" %>
  <% if @trace.inserted %>
    <img src="<%= url_for :controller => "traces", :action => "picture", :id => @trace.id, :display_name => @trace.user.display_name %>">
  <% else %>
    <span class="text-danger"><%= t ".pending" %></span>
  <% end %>
<% end %>

<table class="table table-borderless table-sm">
  <tr>
    <th><%= t ".filename" %></th>
    <td><%= @trace.name %> (<%= link_to t(".download"), trace_data_path(@trace) %>)</td>
  </tr>
  <tr>
    <th><%= t ".uploaded" %></th>
    <td><%= l @trace.timestamp, :format => :friendly %></td>
  </tr>
  <% if @trace.inserted? %>
  <tr>
    <th><%= t ".points" %></th>
    <td><%= number_with_delimiter(@trace.size) %></td></tr>
  <tr>
    <th><%= t ".start_coordinates" %></th>
    <td>
      <div class="d-inline">
        <%= t ".coordinates_html",
              :latitude => tag.span(number_with_delimiter(@trace.latitude), :class => "latitude"),
              :longitude => tag.span(number_with_delimiter(@trace.longitude), :class => "longitude") %>
      </div>
      (<%= link_to t(".map"), :controller => "site", :action => "index", :mlat => @trace.latitude, :mlon => @trace.longitude, :anchor => "map=14/#{@trace.latitude}/#{@trace.longitude}" %> / <%= link_to t(".edit"), :controller => "site", :action => "edit", :gpx => @trace.id, :anchor => "map=14/#{@trace.latitude}/#{@trace.longitude}" %>)</td>
  </tr>
  <% end %>
  <tr>
    <th><%= t ".owner" %></th>
    <td><%= link_to @trace.user.display_name, user_path(@trace.user) %></td>
  </tr>
  <tr>
    <th><%= t ".description" %></th>
    <td><%= @trace.description %></td>
  </tr>
  <tr>
    <th><%= t ".tags" %></th>
    <td>
    <% unless @trace.tags.empty? %>
      <%= safe_join(@trace.tags.collect { |tag| link_to tag.tag, :controller => "traces", :action => "index", :tag => tag.tag, :id => nil }, ", ") %>
    <% else %>
      <i><%= t ".none" %></i>
    <% end %>
    </td>
  </tr>
  <tr>
    <th><%= t ".visibility" %></th>
    <td><%= t "traces.visibility.#{@trace.visibility}" %></td>
  </tr>
</table>

<% if current_user && (current_user==@trace.user || current_user.administrator? || current_user.moderator?) %>
  <div>
    <% if current_user == @trace.user %>
      <%= link_to t(".edit_trace"), edit_trace_path(@trace), :class => "btn btn-outline-primary" %>
    <% end %>
    <%= link_to t(".delete_trace"), { :controller => "traces", :action => "destroy", :id => @trace.id }, { :method => :delete, :class => "btn btn-outline-danger", :data => { :confirm => t(".confirm_delete") } } %>
  </div>
<% end %>